# Advanced Slicing in Kosh

This notebook is for **advanced** users.

We will show how to re-implement `__getitem__` in Kosh's Loaders, Transformers or Operators, to allow efficient slicing.

## Concepts

In early version of Kosh (1.x) , Transformers and Loaders would only allow to retrieve a feature in its whole. Loaders could be fed user-defined keywords to subset a feature but nothing general was in place.

Similarly transforemrs would get the entire feature before processing it.

Starting with 2.0, Kosh offers the possibility to slice feature at any level, allowing for efficient data retrieval.

In this notebook will assume we have a very big dataset that cannot fit in memory at once. We will show how Kosh can still work on *chunks* of the datasets.

# The Big Dataset

To demonstrate Kosh cpabilities we will create a custom loader, that returns range(N) with N coming from the source name itself. With N very big a regular ingestion is no longer possible.

# Standard Loader

Let's create this loader in its most basic form. 



In [1]:
import kosh
import os
import numpy


class MyBasicLoader(kosh.KoshLoader):
    types = {"range": ["numpy", ]}

    def extract(self):
        # ridiculous over-simplification, use name to get length!
        length = int(os.path.basename(self.obj.uri))
        return numpy.arange(length)

    def list_features(self):
        return ["range", ]


Let's add this loader to Kosh and try to retrieve a few fake datasets

It's a very simple loader, that can handle returning a single item or a slice.

Note that we didn't implement things like ellipis, etc...

In [2]:
store = kosh.create_new_db("data_slicing.sql")
store.add_loader(MyBasicLoader)
ds = store.create()
# associate a fake source with it
# name is "5" so we should return numpy.arange(5)
ds.associate("5", mime_type="range")
rg = ds["range"]
print("values:", rg())

values: [0 1 2 3 4]


So far all is good. But now let's assume we need a really long range

In [3]:
ds = store.create()
# associate a fake source with it
# name is "5" so we should return numpy.arange(5)
ds.associate("500000000000000000000000", mime_type="range")
rg = ds["range"]
try:
    print("values:", rg())
except Exception as error:
    print("We failed with the following error:", error)

We failed with the following error: Maximum allowed size exceeded


Maybe slicing this would work

In [4]:
try:
    print("values:", rg[:3])
except Exception as error:
    print("We failed with the following error:", error)

We failed with the following error: Maximum allowed size exceeded


Unfortunately no, this is because our loader does not explicitly define a way to slice the data.

Let's solve this by adding a `__getitem__` function to our loader

It's a very simple loader, that can handle returning a single item or a slice.

Note that we didn't implement things like ellipis, etc...

In [5]:
import kosh

class MySlicingLoader(MyBasicLoader):
    types = {"range": ["numpy", ]}
    def __getitem__(self, key):
        length = int(os.path.basename(self.obj.uri))
        if isinstance(key, int):
            if 0 <= key < length:
                return numpy.array(key)
            elif -length <= key < 0:
                return length - (key + 1)
            else:
                raise ValueError("Index {} is out of range".format(key))
        elif isinstance(key, slice):
            start = key.start
            stop = key.stop
            step = key.step
            if start is None:
                start = 0
            if step is None:
                step = 1
            if stop is None:
                stop = length
            if -length < start < 0:
                start += length
            if -length < stop < 0:
                stop += length
            return numpy.arange(start, stop, step, dtype=numpy.float64)
        else:
            raise ValueError("Invalid key value: {}".format(key))


Now let's remove the old loader and add this to our store

In [6]:
del(store.loaders["range"])
store.add_loader(MySlicingLoader)
rg = ds["range"]
print(rg[:5])
print(rg[2020:2025])

[0. 1. 2. 3. 4.]
[2020. 2021. 2022. 2023. 2024.]


Problem solved! we can now easilt slice and dice our data at the loader level?

But what about Transformers or Operators?

Let's create a transformer that multiplies the data by 2

In [7]:
class Times2(kosh.transformers.KoshTransformer):
    types = {"numpy":["numpy",]}
    def transform(self, input_, format):
        return input_*2.

Let's apply this transformer on our sliced data

In [8]:
rg = ds.get_io_graph("range", transformers=[Times2(),])
try:
    print(rg[:5])
except Exception as err:
    print("We run into the error again!: ", err)

We run into the error again!:  Maximum allowed size exceeded


We need to implement the propagation function for `__getitem__`: `__getitem__propagate__`


In [9]:
class Times2Propagate(Times2):
    def __getitem_propagate__(self, key):
        return key
rg = ds.get_io_graph("range", transformers=[Times2Propagate(),])
rg[:5]

array([0., 2., 4., 6., 8.])

It works! 

So why didn't kosh implement this function by default?

Well this can be tricky let's examine the case where the transformers also flips the data. 
Let's apply it to a smaller dataset so we can follow the logic better

In [10]:
class FlipPropagate(kosh.transformers.KoshTransformer):
    def __getitem_propagate__(self, key):
        return key
    def transform(self, input_, format):
        return input_[::-1] * 2.
ds = store.create()
ds.associate("20", mime_type="range")
rg = ds.get_io_graph("range", transformers=[FlipPropagate(),])
rg[:5]

array([8., 6., 4., 2., 0.])

Compare to the full solution

In [11]:
rg[:]

array([38., 36., 34., 32., 30., 28., 26., 24., 22., 20., 18., 16., 14.,
       12., 10.,  8.,  6.,  4.,  2.,  0.])

In our first case we should have received: array([38., 36., 34., 32., 30.])

So what went wrong?

Well our transformer dutifully propageted to our loader that we were only interested in the first 5 elements. As a result the loader sent back 0, 1, 2, 3, 4 which our transformer appropriately flipped and timed by 2.

So what should we do. Well we need to implement `__getitem_propagate__` n such a way that the loaders returns the **last** 5 elements not the first ones.

Here again we will over simplify and implement only int and slice as possible keys.

In [12]:
class FlipPropagateOk(kosh.transformers.KoshTransformer):
    def __getitem_propagate__(self, key):
        if isinstance(key, int):
            return -1 - key
        elif isinstance(key, slice):
            if key.stop is None:
                start = 0
            else:
                start = -key.stop
            if key.start is None:
                stop = None
            else:
                stop = -key.start
            return slice(start, stop, key.step)
        else:
            return slice(None, None, None)

    def transform(self, input_, format):
        return input_[::-1] * 2.
rg = ds.get_io_graph("range", transformers=[FlipPropagateOk(),])
rg[:5]

array([38., 36., 34., 32., 30.])

Hurray! It works!

The same is true for Operators.

In [13]:
class ADD(kosh.KoshOperator):

    types = {"numpy": ["numpy", ]}

    def operate(self, *inputs, **kargs):
        out = inputs[0]
        for input_ in inputs[1:]:
            out += input_
        return out

    def __getitem_propagate__(self, key):
        return key

rg1 = ds.get_io_graph("range", transformers=[FlipPropagateOk(),])
rg2 = ds.get_io_graph("range", transformers=[Times2Propagate()])

add = ADD(rg1, rg2)

print(add[5:-6])

[38. 38. 38. 38. 38. 38. 38. 38. 38.]
